In [7]:
import pandas as pd
import numpy as np
info = pd.read_csv("C://Users//qiao//Downloads//submit_result.csv",index_col=0)

从数据表示中提取正确的数据对于完成工作至关重要。然而，数据并不总是以我们想要的格式出现在内存中。有时候我们必须自己做更多的工作来为手头的任务重新格式化它。本教程将涵盖不同的操作，我们可以应用到我们的数据得到输入“刚刚好”。

将pandas的显示选项display.max_rows设置为5，即在显示DataFrame或Series对象时，最多只显示5行数据。这个设置可以用于控制在输出大型数据集时，限制显示的行数，以防止输出过多数据导致界面混乱或占用过多的空间。

In [14]:
pd.set_option('display.max_rows', 8)

In [15]:
info

上部温度1       上部温度2       上部温度3       上部温度4       上部温度5       上部温度6  \
序号                                                                              
1      299.718360  366.500427  443.564463  520.588520  575.107407  657.685432   
2      304.346405  373.119891  448.033343  520.963782  575.840164  658.441574   
3      305.599822  373.356982  446.307020  520.318549  575.478573  658.738011   
4      304.491133  373.152765  447.978744  520.833906  575.997509  658.406977   
...           ...         ...         ...         ...         ...         ...   
11421  268.985784  341.460451  420.270750  504.477544  566.244881  642.360081   
11422  268.187569  342.027558  418.512886  506.975244  567.223651  641.656368   
11423  267.611923  342.614686  419.576709  504.011550  566.335652  642.739453   
11424  268.477168  342.330290  419.160543  504.508342  568.206377  642.150697   

            上部温度7       上部温度8       上部温度9      上部温度10  ...       下部温度8  \
序号                                                     ...               
1      734.073158  837.000503  836.992058  836.992509  ...  836.987561   
2      734.778881  837.036314  836.991788  836.997258  ...  837.037068   
3      735.060662  837.039977  837.009962  836.993982  ...  836.990481   
4      734.846715  837.048583  837.002248  837.007421  ...  837.037048   
...           ...         ...         ...         ...  ...         ...   
11421  713.256490  789.296986  787.704975  787.547634  ...  789.092031   
11422  713.829987  789.275871  787.599543  787.404667  ...  789.121659   
11423  713.302542  789.208577  787.716538  787.466510  ...  789.089384   
11424  713.618801  789.060602  787.714911  787.424552  ...  789.124140   

            下部温度9      下部温度10      下部温度11      下部温度12      下部温度13      下部温度14  \
序号                                                                              
1      826.651661  837.001688  836.973254  836.987646  836.984995  837.014752   
2      836.860990  837.004078  836.996945  836.978739  837.017583  836.996405   
3      837.011626  836.999128  837.003873  837.000021  836.995137  836.990254   
4      830.182047  837.007092  836.996802  837.009205  837.009207  837.006841   
...           ...         ...         ...         ...         ...         ...   
11421  772.792849  787.548251  792.078790  790.737499  787.660023  780.438238   
11422  780.271304  787.356966  791.941190  790.722414  787.573644  780.264086   
11423  765.784247  787.381125  791.997867  790.790275  787.397333  780.329093   
11424  763.301228  787.371317  791.952300  790.742289  787.461375  780.429081   

           下部温度15      下部温度16      下部温度17  
序号                                         
1      836.989262  837.388292  749.974553  
2      836.985994  837.054367  750.047734  
3      837.004073  837.127619  750.010020  
4      836.980559  837.100721  750.103786  
...           ...         ...         ...  
11421  764.846056  712.703782  634.117198  
11422  764.749560  712.956878  635.027758  
11423  764.698197  712.976412  634.997220  
11424  764.711263  712.936780  634.887393  

[11424 rows x 34 columns]

In [16]:
info.describe()

上部温度1         上部温度2         上部温度3         上部温度4         上部温度5  \
count  11424.000000  11424.000000  11424.000000  11424.000000  11424.000000   
mean     302.408509    386.270302    484.328879    578.414558    651.475947   
std       41.659075     51.119688     67.059835     74.989518     93.851768   
min      241.912054    305.874930    402.532254    499.849874    544.886179   
25%      268.460499    345.462809    422.734064    508.832634    564.911927   
50%      282.800955    363.392166    437.626299    519.335668    577.808531   
75%      326.615563    424.839138    556.512136    660.443861    755.221020   
max      401.738846    493.887384    581.479098    677.889255    766.263409   

              上部温度6         上部温度7         上部温度8         上部温度9        上部温度10  \
count  11424.000000  11424.000000  11424.000000  11424.000000  11424.000000   
mean     738.989485    817.698305    872.353234    871.710135    871.711059   
std      100.084803     95.028376     53.713562     53.663770     53.822486   
min      627.790191    706.390076    786.689872    744.822389    737.734442   
25%      646.725786    733.502984    833.190311    833.358756    833.240581   
50%      657.500138    739.290838    849.713298    847.365439    847.233452   
75%      850.273404    925.830141    928.133660    928.040066    928.135397   
max      856.746374    936.997667    944.587580    943.394579    943.513975   

       ...         下部温度8         下部温度9        下部温度10        下部温度11  \
count  ...  11424.000000  11424.000000  11424.000000  11424.000000   
mean   ...    872.339561    805.178700    871.768067    872.310155   
std    ...     53.943948    371.054592     53.860250     52.751467   
min    ...    786.450329  -2236.635535    732.601502    760.114258   
25%    ...    833.532192    810.624242    833.426045    833.603313   
50%    ...    849.031733    918.340255    847.504107    847.492529   
75%    ...    928.121341    998.869054    927.997000    927.881527   
max    ...    945.385442   2045.705564    944.053658    942.952685   

             下部温度12        下部温度13        下部温度14        下部温度15        下部温度16  \
count  11424.000000  11424.000000  11424.000000  11424.000000  11424.000000   
mean     872.393030    870.453999    867.016949    865.385650    838.876513   
std       53.064810     52.791369     55.452788     58.139264     56.489632   
min      781.224403    738.274128    725.288571    720.598839    710.861736   
25%      833.306623    833.495275    829.496281    828.922600    829.982083   
50%      847.460616    847.546872    847.739455    847.934529    847.513922   
75%      927.810136    928.055533    927.966684    928.131213    855.745457   
max      948.159718    943.583315    943.908358    944.446284    932.845627   

             下部温度17  
count  11424.000000  
mean     745.450389  
std       58.060366  
min      618.412649  
25%      699.691552  
50%      750.057382  
75%      754.643945  
max      857.239588  

[8 rows x 34 columns]

想查看具体的某一列的数据：

In [18]:
statistics = info['上部温度1'].describe()
print(statistics)

count    11424.000000
mean       302.408509
std         41.659075
min        241.912054
25%        268.460499
50%        282.800955
75%        326.615563
max        401.738846
Name: 上部温度1, dtype: float64


In [25]:
data = {
    'A': [1, 2, 3, 1, 2],
    'B': [10, 20, 30, 40, 40]
}
df = pd.DataFrame(data)
df

A   B
0  1  10
1  2  20
2  3  30
3  1  40
4  2  40

unique函数返回仅出现一次的数据

In [21]:
info['上部温度1'].unique()

array([299.71836044, 304.3464049 , 305.59982227, ..., 268.18756878,
       267.61192333, 268.47716788])

In [26]:
print(df['B'].unique())
print(df['A'].unique())

[10 20 30 40]
[1 2 3]


value_counts()函数用来统计DataFrame或Series中各个唯一值出现的频次的方法。它返回一个包含唯一值和它们对应出现频次的Series对象。

In [37]:
value_counts_A = df['B'].value_counts()
value_counts_A

40    2
10    1
20    1
30    1
Name: B, dtype: int64

在pandas中，map()函数是用于对DataFrame或Series中的元素进行映射转换的方法。它可以接受一个字典、Series或函数作为参数，并将每个元素映射到相应的转换结果。

对于Series，map()函数对其中的每个元素应用映射转换，并返回一个新的Series对象，其中包含转换后的值。

对于DataFrame，map()函数可以用于对其中的某一列（Series）进行映射转换，并返回转换后的新列。它也可以用于对整个DataFrame中的所有元素进行映射转换。

In [39]:
# 创建一个示例DataFrame
data = {
    'A': [1, 2, 3, 4, 5],
    'B': ['apple', 'banana', 'orange', 'apple', 'banana']
}
df1 = pd.DataFrame(data)

# 使用字典进行映射转换，将'A'列的值映射为对应的英文单词
fruit_mapping = {1: 'apple', 2: 'banana', 3: 'orange', 4: 'grape', 5: 'pineapple'}
df1['A_mapped'] = df1['A'].map(fruit_mapping)
print(df1)

# 使用函数进行映射转换，将'B'列的水果名称转换为大写形式
df1['B_upper'] = df1['B'].map(lambda x: x.upper())
df1

   A       B   A_mapped
0  1   apple      apple
1  2  banana     banana
2  3  orange     orange
3  4   apple      grape
4  5  banana  pineapple


A       B   A_mapped B_upper
0  1   apple      apple   APPLE
1  2  banana     banana  BANANA
2  3  orange     orange  ORANGE
3  4   apple      grape   APPLE
4  5  banana  pineapple  BANANA

上述代码中，```df1['B'].map(lambda x: x.upper())```的含义是：使用map()方法对 'B' 列中的每个元素应用一个自定义的转换函数。在这里，我们使用了一个lambda函数，它接受一个参数 x，表示 'B' 列中的每个元素。x.upper() 表示将 x 转换为大写形式。这样，对 'B' 列中的每个元素进行转换后，map()方法返回一个新的Series对象，其中包含了转换后的大写形式的元素。

In [44]:
# 创建一个示例DataFrame
datalist = {
    'A': [1, 2, 3, 4, 5],
    'B': [10, 20, 30, 40, 50]
}
df_1 = pd.DataFrame(datalist)

# 对每个元素应用自定义函数，平方'A'列和'B'列中的元素
def square(x):
    return x ** 2

df_squared = df_1.apply(square)
df_squared

A     B
0   1   100
1   4   400
2   9   900
3  16  1600
4  25  2500

In [48]:
column_sum = df_1.apply(sum)#对列求和
column_sum

A     15
B    150
dtype: int64

运用axis参数时：

In [51]:
# 创建一个示例DataFrame
data3 = {
    'A': [2, 4, 6, 8, 10],
    'B': [10.1, 20.2, 30.3, 40.4, 50.5]
}
df3 = pd.DataFrame(data3)

# 定义一个自定义函数，例如将行中的元素相加
def custom_function(row):
    return row['A'] + row['B']

# 使用apply()函数对某一行应用自定义函数，axis=1表示按行操作
df3[0] = df3.apply(custom_function, axis=1)
df3

A     B     0
0   2  10.1  12.1
1   4  20.2  24.2
2   6  30.3  36.3
3   8  40.4  48.4
4  10  50.5  60.5